{% set name = "dataconf" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataconf-{{ version }}.tar.gz
  sha256: f31967915b69dfef1dc8236723ccf8b333d33613e06e9c92ac92e5551ffe04b4

build:
  number: 0
  noarch: python
  entry_points:
    - dataconf = dataconf.cli:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.8
  run:
    - pyhocon >=0.3.59,<0.4.0
    # pyparsing~=2.0 needed for pyhocon 0.3.59
    - pyparsing ~=2.0
    - python >=3.8
    - python-dateutil >=2.8.2,<3.0.0

test:
  imports:
    - dataconf
  commands:
    - pip check
    - dataconf --help
  requires:
    - pip

about:
  home: https://github.com/zifeo/dataconf
  summary: Simple dataclasses configuration management for Python with hocon/json/yaml/properties/env-vars/dict support.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
