{% set name = "dataconf" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataconf-{{ version }}.tar.gz
  sha256: d94bcde07b25a166c0d5f7187abf3386afe43980d2d101ec6edbca8026e9de44

build:
  number: 0
  noarch: python
  entry_points:
    - dataconf = dataconf.cli:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.8
  run:
    - pyhocon >=0.3.59,<0.4.0
    - pyparsing ~=2.0
    - python >=3.8
    - python-dateutil >=2.8.2,<3.0.0
    - pyyaml >=6.0

test:
  imports:
    - dataconf
  commands:
    - pip check
    - dataconf --help
  requires:
    - pip

about:
  home: https://github.com/zifeo/dataconf
  summary: Simple dataclasses configuration management for Python with hocon/json/yaml/properties/env-vars/dict support
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zifeo
    - thewchan
